title = "Chia Yong Kang"
baseURL = "https://chiayong.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[services]
  [services.googleAnalytics]
    ID = "G-D5HBRC62LK"

[params]
  author = "Chia Yong Kang"
  description = "Web3 Engineer"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Yong Kang"
    url = "chiayong.com"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:chiayongkang@hotmail.com"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/yongkangc"

[permalinks]
  "/" = "/:contentbasename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/articles"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true
